version: "3.8"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            MONGODB_URL: mongodb+srv://gowtham-cyber-max:GoWtHaM%404262472@book.iub25xr.mongodb.net/?retryWrites=true&w=majority&appName=book
        networks:
            - mynetwork

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge